name: Trevas Jupyter CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check code formatting thanks to Spotless
        run: ./mvnw spotless:check
  test:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Test Trevas Jupyter
        run: ./mvnw test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Package Trevas Jupyter
        run: ./mvnw package
  deploy-dockerhub:
    needs: package
    if: github.repository == 'inseefrlab/trevas-jupyter' &&
      startsWith(github.ref, 'refs/tags/v') &&
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate tag format and extract version
        id: extract_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag '$TAG' does not match vX.Y.Z format. Skipping."
            exit 1
          fi
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"

      - name: Set current version
        run: ./mvnw -B versions:set -DnewVersion=${{ steps.extract_version.outputs.VERSION }} -DprocessAllModules -DgenerateBackupPoms=false

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]

      - name: Build with Maven
        run: ./mvnw -B clean package

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5.7.0
        with:
          images: inseefrlab/trevas-jupyter

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            inseefrlab/trevas-jupyter:${{ steps.extract_version.outputs.VERSION }}
            inseefrlab/trevas-jupyter:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
