name: Trevas Jupyter CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Check code formatting thanks to Spotless
        run: ./mvnw spotless:check
  test:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Test Trevas Jupyter
        run: ./mvnw test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Package Trevas Jupyter
        run: ./mvnw package
  deploy-dockerhub:
    needs: package
    if: github.repository == 'inseefrlab/trevas-jupyter' &&
        github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Set current version
        run: ./mvnw -B versions:set -DnewVersion=${GITHUB_REF##*/} -DprocessAllModules -DgenerateBackupPoms=false
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          githubServer: false
          servers: |
            [{
                "id": "Github",
                "username": "${{ secrets.GH_PACKAGES_USERNAME }}",
                "password": "${{ secrets.GH_PACKAGES_PASSWORD }}"
            }]
      - name: Build with Maven
        run: ./mvnw -B clean package
      - run: ls
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5.5.1
        with:
          images: inseefrlab/trevas-jupyter # list of Docker images to use as base name for tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/main' && 'inseefrlab/trevas-jupyter:latest' || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}